// AUTO-GENERATED stub — overwritten by `npx convex dev`
// Do not edit this file manually.

/* eslint-disable @typescript-eslint/no-explicit-any */
export declare const api: any;
export declare const internal: any;
