// AUTO-GENERATED stub — overwritten by `npx convex dev`
// Do not edit this file manually.
import type { GenericId } from "convex/values";

// Stub Id type that matches the real Convex Id<TableName> signature.
export type Id<TableName extends string> = GenericId<TableName>;

// Stub Doc type — real version is derived from schema.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Doc<TableName extends string> = { _id: Id<TableName>; _creationTime: number } & Record<string, any>;
