// AUTO-GENERATED stub — overwritten by `npx convex dev`
// Do not edit this file manually.

/* eslint-disable @typescript-eslint/no-explicit-any */
export declare function mutation(def: any): any;
export declare function query(def: any): any;
export declare function action(def: any): any;
export declare function internalMutation(def: any): any;
export declare function internalQuery(def: any): any;
export declare function internalAction(def: any): any;
